apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-first-app-cron
spec:
  schedule: "*/5 * * * *"   # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: lizzyy/saas:latest
            command:
              - python
              - manage.py
              - my_cron_task
          restartPolicy: OnFailure